// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("bs-platform/lib/js/curry.js");
var ReasonReact = require("reason-react/src/ReasonReact.js");
var Js_undefined = require("bs-platform/lib/js/js_undefined.js");
var ReactCodemirror2 = require("react-codemirror2");

function make(autoFocus, style, value, editorDidMount, onChange, options, children) {
  return ReasonReact.wrapJsForReason(ReactCodemirror2.UnControlled, {
              autoFocus: autoFocus !== undefined && autoFocus ? true : false,
              style: Js_undefined.fromOption(style),
              value: Js_undefined.fromOption(value),
              onBeforeChange: (function (_editor, _data, value) {
                  if (onChange !== undefined) {
                    return Curry._1(onChange, value);
                  } else {
                    return /* () */0;
                  }
                }),
              editorDidMount: Js_undefined.fromOption(editorDidMount),
              options: Js_undefined.fromOption(options)
            }, children);
}

exports.make = make;
/* ReasonReact Not a pure module */
