// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


function replace_program_with(program, text) {
  return program[/* prelude */0] + (text + program[/* prologue */2]);
}

exports.replace_program_with = replace_program_with;
/* No side effect */
