// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Jest = require("@glennsl/bs-jest/src/jest.js");
var Util$ReactTemplate = require("../src/Util.bs.js");

function quick_test(name, p, replace, result) {
  describe(name, (function () {
          return Jest.test("toBe", (function (param) {
                        return Jest.Expect[/* toBe */2](result, Jest.Expect[/* expect */0](Util$ReactTemplate.replace_program_with(p, replace)));
                      }));
        }));
  return /* () */0;
}

quick_test("quick start", /* record */[
      /* prelude */"",
      /* selection */"f(5)",
      /* prologue */""
    ], "f(5 - 1) + f(5 - 2)", "f(5 - 1) + f(5 - 2)");

quick_test("eval param", /* record */[
      /* prelude */"f(",
      /* selection */"5 - 1",
      /* prologue */") + f(5 - 2)"
    ], "4", "f(4) + f(5 - 2)");

exports.quick_test = quick_test;
/*  Not a pure module */
